---
- name: install docker-py
  pip:
    name: docker-py
    state: present

- name: ensure rancher image is present
  docker_image:
    name: rancher/server
    tag: v{{rancher_version}}
    state: present

- name: start rancher
  docker_container:
    name: rancher-server
    image: rancher/server:v{{rancher_version}}
    detach: True
    network_mode: bridge
    restart_policy: unless-stopped
    published_ports:
      - 8080:8080

- name: create ssh keypair folder for rancher
  command: "mkdir -p /root/rancher_keys"

- name: generate ssh keypair for rancher
  command: "ssh-keygen -f /root/rancher_keys/id_rsa -N ''"

- name: install rancher ssh keypair
  shell: "docker cp /root/rancher_keys/id_rsa rancher-server:/ && docker cp /root/rancher_keys/id_rsa.pub rancher-server:/"
