---
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

- hosts: all
  roles:
    - common

- hosts: role=rancher,role=worker
  roles:
    - docker

- hosts: role=rancher
  roles:
    - rancher
